name: Update main.txt

on:
  push:
    paths:
      - 'contributable_lists/*.txt'
    branches:
      - main

jobs:
  auto-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run update script
        run: |
          git pull
          npm run refresh-main

      - name: Commit refresh main.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add main.txt
          git commit -m "Auto-update main.txt" || echo "No changes"
          git push
