name: Update extensions.txt

on:
  push:
    paths:
      - 'contributable_lists/*.txt'
    branches:
      - main

jobs:
  auto-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run update script
        run: |
          git pull
          npm run refresh-list

      - name: Commit refresh extensions.txt
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add extensions.txt
          git commit -m "Auto-update extensions.txt" || echo "No changes"
          git push https://DPetkovic-dev:${GH_PAT}@github.com/${REPO} HEAD:main
